### ISSUE TITLE
"Found invalid data while decoding"

### ISSUE THREAD

**Issue by Erlite** [SteamDatabase/ValveKeyValue#11]
I'm currently working on a vmf-to-json program, and while reading a VMF file and attempting to deserialize it, I get `"Found invalid data while decoding"`

Here's the VMF file: https://hastebin.com/kojimugafo.pl

It's only a simple brush, and I don't see why it shouldn't work. I'm reading the file directly with a FileStream.

**Comment by xPaw** [comment]
It would help if you could provide more information, and perhaps a reduced test case if possible.

**Comment by psychonic** [comment]
VMF files are not KeyValues files. They have no root node.

**Comment by Erlite** [comment]
Ah might be why, sorry ^^
