### ISSUE TITLE
Implement the ToType and other methods on KVCollectionValue

### ISSUE THREAD

**Issue by CitadelCore** [SteamDatabase/ValveKeyValue#15]
We should probably implement the `ToType` method at least. Otherwise, it's impossible to deserialise a KeyValues1 document to a `Dictionary<string, name>` where `name` is replaced with your class name.

I'll see if I can work out a way to implement these later on.

**Comment by Outzzz** [comment]
i have some binary data, 
```
MessageObject:{       object 
    lineitems:{             object 
    0:{                         object
	"description":" *****", 		string 1
	"amount":249   int64 10
	"quantity": 1  	uint32 2
	}		end    8
    },			end    8
}			end    8
			end    8
```
how should i define my custom class,  the count of itmes is not fixed.
 list<item> Lineitems or dictionary<string, item> Lineitems not working

here is the test data
```
 0x01, 0x00, 0x4D, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4F, 0x62, 0x6A, 0x65, 0x63, 0x74, 0x00, 0x00, 0x6C, 0x69, 0x6E, 0x65, 0x69, 0x74, 0x65, 0x6D, 0x73, 0x00, 0x00, 0x30, 0x00, 0x01, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6F, 0x6E, 0x00, 0x4F, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6F, 0x6E, 0x20, 0x48, 0x79, 0x64, 0x72, 0x61, 0x20, 0x43, 0x61, 0x73, 0x65, 0x20, 0x4B, 0x65, 0x79, 0x00, 0x0A, 0x61, 0x6D, 0x6F, 0x75, 0x6E, 0x74, 0x00, 0x78, 0x1E, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x71, 0x75, 0x61, 0x6E, 0x74, 0x69, 0x74, 0x79, 0x00, 0x01, 0x00, 0x00, 0x00, 0x08, 0x00, 0x31, 0x00, 0x01, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6F, 0x6E, 0x00, 0x53, 0x70, 0x65, 0x63, 0x74, 0x72, 0x75, 0x6D, 0x20, 0x43, 0x61, 0x73, 0x65, 0x20, 0x4B, 0x65, 0x79, 0x00, 0x0A, 0x61, 0x6D, 0x6F, 0x75, 0x6E, 0x74, 0x00, 0x78, 0x1E, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x71, 0x75, 0x61, 0x6E, 0x74, 0x69, 0x74, 0x79, 0x00, 0x01, 0x00, 0x00, 0x00, 0x08, 0x08, 0x08, 0x08
```

**Comment by yaakov-h** [comment]
If it's a custom class name then KVCollectionValue has to know about classes defined outside of the library.

We could potentially throw the door open to custom TypeConverters, which means you would need to decorate your custom types with a `TypeConverterAttribute` and implement a subclass of `TypeConverter`...

**Comment by xPaw** [comment]
Would `ISerializable` do the trick?

**Comment by yaakov-h** [comment]
Maybe, it would need further investigation.

Closing in favour of #18 as it's a bit broader, and `ToType` is the wrong way to go.
