### ISSUE TITLE
KVObject[string] returns KVValue which is impossible to enumerate

### ISSUE THREAD

**Issue by xPaw** [SteamDatabase/ValveKeyValue#21]
> KVObject["string"] returns a KVValue, but if it has children i can't access that
debuggers shows 'children', but i can only call ToXXX() on it
it gives me the this[string] accessor, but i can't enumerate the children if I dont know the keys
calling tostring on it would indicate its KVCollectionValue due to [Collection], but if I try to foreach() it says KVValue has no GetEnumerator

Example code for Steam's config.vdf:
```csharp
            using var fs = new FileStream(filename, FileMode.Open, FileAccess.Read, FileShare.ReadWrite);
            var data = KVSerializer.Create(KVSerializationFormat.KeyValues1Text).Deserialize(fs);

            var depots = data["Software"]["Valve"]["Steam"]["depots"];

            foreach (var depot in depots) // KVValue has no GetEnumerator()
            {

            }
```

**Comment by yaakov-h** [comment]
The whole API probably needs to be revisited, but in the meantime you can cast it, i.e.:

```csharp
var depots = data["Software"]["Valve"]["Steam"]["depots"];

foreach (var depot in (IEnumerable<KVObject>)depots)
{
    Console.WriteLine(depot.Name);
}
```

**Comment by yaakov-h** [comment]
Closing to leave this to #30.
