### ISSUE TITLE
Bracketed value is being detected as a conditional

### ISSUE THREAD

**Issue by xPaw** [SteamDatabase/ValveKeyValue#28]
I had a branch with test case here: https://github.com/SteamDatabase/ValveKeyValue/compare/bracketed-value

System.IO.InvalidDataException : Found conditional while in state InObjectBetweenKeyAndValue.

**Comment by yaakov-h** [comment]
O_o never seen that before...

**Comment by xPaw** [comment]
I guess the fix is to simply get rid of `Found conditional while in state InObjectBetweenKeyAndValue.` and assume such conditional is a value.

**Comment by yaakov-h** [comment]
I guess so. Is it actually valid KV though, or is it just a typo?

I find it very strange that `$envmaptint` has quotes but then `$envmapsaturation` does not.

**Comment by yaakov-h** [comment]
The latest tier1 code I have can't parse this, so I suspect it may have just been a typo.

```text
Conditional Error: Bad expression token: .
KeyValues Error: KV Conditional Evaluation Error in file brackets_without_quotes.vdf
VertexLitGeneric,
KeyValues Error: RecursiveLoadFromBuffer:  got } in key in file brackets_without_quotes.vdf
VertexLitGeneric,
```
