### ISSUE TITLE
A string where backwards slash is at the end of a a string does not parse

### ISSUE THREAD

**Issue by xPaw** [SteamDatabase/ValveKeyValue#31]
```
"Test"
{
  "BuildOutput" "..\output\"
}
```

It throws `Found end of file while trying to read token.` because it always thinks `\` is an escape, even if `HasEscapeSequences` is false.

Example from: https://partner.steamgames.com/doc/sdk/uploading
Test case: https://github.com/SteamDatabase/ValveKeyValue/tree/backslash-no-escape

**Comment by xPaw** [comment]
This happened in VRF, with a string like `"saveDirectory"	"B:\"`, which is produced by `Serialize`, so this serialize-unserialize does not round trip correctly.

**Comment by yaakov-h** [comment]
How are we supposed to tell the difference between "this `\` is an escape for the subsequent `"`" and "this `\` is the final character followed by a `"`"?

Or should we only differentiate if `HasEscapeSequences` is false?

**Comment by xPaw** [comment]
I don't know. Half of the problem is that serialize produces output it can't parse.

**Comment by yaakov-h** [comment]
I think we could fix serialize to escape it but for deserialising I don't think we can win.
I'm confused because it seems to me that we have conflicting scenarios:

- https://github.com/SteamDatabase/ValveKeyValue/commit/c14171ee1f676a8503adc91f259a9b70bd431e2b says that a backslash-quote must always be escaped, even if we don't escape other characters such as `\r` (i.e.  `HasEscapeSequences`)
- this issue says that a backslash-quote should not be escaped if we disable `HasEscapeSequences`

How does Valve's KV implementation handle their own sample VDF?

**Comment by xPaw** [comment]
In the commit you link, should this be `\\\\` to actually print an escaped back slash?

https://github.com/SteamDatabase/ValveKeyValue/commit/c14171ee1f676a8503adc91f259a9b70bd431e2b#diff-0fb7d683ac0056cacc4d6c4cf577a37c5646ed452b8c923d9b9ba87110bb2b5eR198-R200

**Comment by yaakov-h** [comment]
That's KVToken_Reader._ Did you mean that, or do you mean that _serialising_ the `\` should be `\\`?

We do that here, though it doesn't seem to be perfectly symmetric.

https://github.com/SteamDatabase/ValveKeyValue/blob/master/ValveKeyValue/ValveKeyValue/Serialization/KV1TextSerializer.cs#L95

**Comment by xPaw** [comment]
Oh I see, our `HasEscapeSequences` is false by default (same as valve), then I don't really understand how they parse it.

**Comment by yaakov-h** [comment]
Have you confirmed that they _do_ parse it, or is it maybe just a typo in the same code?

**Comment by xPaw** [comment]
That is a good question, unsure how to trivially test it though.

**Comment by yaakov-h** [comment]
when parsing, how can you tell fi you’re “inside” the string or at the end of it?

**Comment by yaakov-h** [comment]
Finally got a test app running with the Source SDK 2013 code, gosh that was tricky.

Valve do manage to parse the sample VDF value when `m_bHasEscapeSequences` is false

When parsing `"..\content\"`, the code that does the parsing eats the first delimiter (`"`) and then continues until it finds another delimiter (`"`), completely ignoring that backslash could be an escape character.

![image](https://user-images.githubusercontent.com/426009/131221402-0dfbadf7-4af2-43dc-8695-3a79f644e451.png)

This suggests to me that what we did for c14171e is not necessarily correct.

If I set `kv->UsesEscapeSequences(true)` then it gives an error, but `LoadFromFile()` still returns true, yielding a garbage KV object, where the string values include newlines and curly braces.:

![image](https://user-images.githubusercontent.com/426009/131221438-3ee21758-6eaf-4566-8fdb-4545c5431d38.png)

Parsing the dodgy `cleanupcmds` text is also questionable Without `UsesEscapeSequences`, it gets garbled:

![image](https://user-images.githubusercontent.com/426009/131221598-26cd7785-a34e-41c6-bb64-d279784aa812.png)

With `UsesEscapeSequences`, Valve get a little bit further but still choke on it, failing to parse it successfully:

![image](https://user-images.githubusercontent.com/426009/131221645-9c325d7b-60dc-4749-9402-af315ae2ab9d.png)

I have no idea though why the string value ends with `"..", as though the next backslash terminates it entirely.

Either they have the same problem parsing TF2's `common`->`cleanupcmds` value, or they have fixed this code between 2013 and 2016 (gosh is VKV really that old already?) and we need their new parser code to adapt.

**Comment by yaakov-h** [comment]
ugh... if you enable `UsesEscapeSequences` and have a `\` not followed by a valid escape char, that char becomes `\0` and therefore the string gets effectively terminated early because C[/C++].

![image](https://user-images.githubusercontent.com/426009/131222187-acef06c0-4464-4f35-a653-fa8cee065d59.png)

**Comment by yaakov-h** [comment]
Using the leaked CS:GO code from April 2018 gives the same results.

The Valve Developer sample file is valid.

The TF2 appinfo from 2016 was _invalid_.
