### ISSUE TITLE
 kvSerializer.Deserialize fails for latest csgo_english.txt

### ISSUE THREAD

**Issue by msmshazan** [SteamDatabase/ValveKeyValue#41]
kvSerializer.Deserialize fails for latest vdf resouce file  csgo_english.txt at https://raw.githubusercontent.com/SteamDatabase/GameTracking-CSGO/master/csgo/resource/csgo_english.txt
 
 The issue seems to it cannot escape /x within the file
 
 
![image](https://user-images.githubusercontent.com/20334207/141774926-4002e824-7a44-4bd4-a409-0915da830f8e.png)

**Comment by msmshazan** [comment]
Does this relate to this https://github.com/SteamDatabase/ValveKeyValue/issues/32 ?

**Comment by yaakov-h** [comment]
hmm, we recently synced up with Valve’s behaviour in #38.

**Comment by xPaw** [comment]
I don't think so, `\x00A2` seems like a unicode codepoint, perhaps it needs to be parsed as-is.

**Comment by msmshazan** [comment]
It's an internal code point i belive becuse in the file
```"GameUI_MakeGamePublicConfTxt" "Press \x00A2 to confirm that you would like to change this private game to a public game that anyone can join."```
00A2 is the cent symbol which doesn't translate properly

**Comment by msmshazan** [comment]
Wait a minute valve did a typo 
![image](https://user-images.githubusercontent.com/20334207/141780473-d216ac42-8603-4622-ad8f-18d282d798e6.png)

**Comment by msmshazan** [comment]
valve pls fix

**Comment by yaakov-h** [comment]
Do Valve parse it as a Unicode codepoint then, or do they parse it literally as backslash x zero zero a two?

there are two different modes to parse kv in after all.

**Comment by msmshazan** [comment]
I believe the latter not as a unicode

**Comment by yaakov-h** [comment]
Then it should be parseable with `KVSerializerOptions.HasEscapeSequences = false` IIRC.

**Comment by msmshazan** [comment]
> Then it should be parseable with `KVSerializerOptions.HasEscapeSequences = false` IIRC.

then I get found conditional error 
![image](https://user-images.githubusercontent.com/20334207/141921152-65950d57-39bb-4314-98a6-42152ceb4a61.png)

**Comment by yaakov-h** [comment]
Ah, they have escaped quotes (`\"`).

I'd really need to know how Valve are parsing it in order to match it. Based on the latest code I have, they would parse this as 

Key: "GameUI_MakeGamePublicConfTxt"
Value: "Press "

As the `\x` gets translated into a null byte (`0x00`).

**Comment by msmshazan** [comment]
Can't we have a parameter in the API where we can ignore parsing some characters?

**Comment by xPaw** [comment]
That's a hack, not a solution.

**Comment by msmshazan** [comment]
True. Can create a separate Github issue for this as a workaround?

**Comment by msmshazan** [comment]
Also Is it necessary to parse everything inside double quotes instead of keeping it as it is?

**Comment by xPaw** [comment]
> Can one create a separate Github issue for this as a workaround?

unless @yaakov-h thinks otherwise, I don't see a good reason to implement this. The problem here is that Valve added new (?) escape code which we don't properly support yet.

> Also Is it necessary to parse everything inside double quotes instead of keeping it as it is?

That's what HasEscapeSequences is supposed to do, but \x seemingly breaks it by parsing it into a null byte, which is the real bug here I think.

**Comment by msmshazan** [comment]
so I stumbled into a new error 
![image](https://user-images.githubusercontent.com/20334207/143022536-96d1ffe4-fdf4-4c92-a10d-b1f33018d8a2.png)

**Comment by yaakov-h** [comment]
As of the 2020 leaked code:

With escaping enabled, Valve fall into the null-byte bug:

```plain
Name: RootObject
    GameUI_MakeGamePublicConfTxt: Press
```

With escaping disable, the backslash-x pattern is a literal backslash, and is not treated as a Unicode character:

```plain
Name: RootObject
    GameUI_MakeGamePublicConfTxt: Press \x00A2 to confirm that you would like to change this private game to a public game that anyone can join.
```

If Valve have added new code to (tier1/KeyValues specifically, rather than the CS:GO engine) to handle `\x` in a special manner then we'll need a reference implementation to compare against.
