### ISSUE TITLE
Support merging of key values for same key

### ISSUE THREAD

**Issue by msmshazan** [SteamDatabase/ValveKeyValue#42]
https://raw.githubusercontent.com/SteamDatabase/GameTracking-CSGO/master/csgo/scripts/items/items_game.txt contains structures like

```
"sticker_kits"
	{
		"0"
		{
			"name"		"default"
			"item_name"		"#StickerKit_Default"
			"description_string"		"#StickerKit_Desc_Default"
		}
		"1"
		{
			"name"		"dh_gologo1"
			"item_name"		"#StickerKit_dh_gologo1"
			"description_string"		"#StickerKit_desc_dh_gologo1"
			"sticker_material"		"dreamhack/dh_gologo1"
			"tournament_event_id"		"1"
		}
		.....
	}
	....
	"sticker_kits"
	{
		"1697"
		{
			"name"		"spray_std_axes_crossed"
			"item_name"		"#SprayKit_std_axes_crossed"
			"description_string"		"#SprayKit_desc_std_axes_crossed"
			"sticker_material"		"default/axes_crossed"
			"item_rarity"		"common"
		}
		"1698"
		{
			"name"		"spray_std_bubble_dead"
			"item_name"		"#SprayKit_std_bubble_dead"
			"description_string"		"#SprayKit_desc_std_bubble_dead"
			"sticker_material"		"default/bubble_dead"
			"item_rarity"		"common"
		}
                ...
 }
 ```
 For this situation only the first set is taken and all others are omitted by the library

**Comment by msmshazan** [comment]
Well looks like all others exist but only the first one is only taken when indexing using the dictionary notiation ( vdf["key1"]["item"]  )

**Comment by yaakov-h** [comment]
Valve's implementation, as of the 2020 leaks, sees it as two unique array properties that happen to have a name collision.

I suspect any apparent merging etc. would be up to the consuming code inside CS:GO.

```plain
Name: RootObject
    Name: sticker_kits
        Name: 0
            name: default
            item_name: #StickerKit_Default
            description_string: #StickerKit_Desc_Default
        Name: 1
            name: dh_gologo1
            item_name: #StickerKit_dh_gologo1
            description_string: #StickerKit_desc_dh_gologo1
            sticker_material: dreamhack/dh_gologo1
            tournament_event_id: 1
    Name: sticker_kits
        Name: 1697
            name: spray_std_axes_crossed
            item_name: #SprayKit_std_axes_crossed
            description_string: #SprayKit_desc_std_axes_crossed
            sticker_material: default/axes_crossed
            item_rarity: common
        Name: 1698
            name: spray_std_bubble_dead
            item_name: #SprayKit_std_bubble_dead
            description_string: #SprayKit_desc_std_bubble_dead
            sticker_material: default/bubble_dead
            item_rarity: common
```

**Comment by msmshazan** [comment]
> I suspect any apparent merging etc. would be up to the consuming code inside CS:GO.

So how would one access the next object which has the same key using dictionary-style indexing?

**Comment by xPaw** [comment]
Have you tried iterating the root object for children instead? Do we actually drop the second object, or is it there?

**Comment by yaakov-h** [comment]
Iterating through children of the root object shows both of them as in that trace above.

If someone calls `->FindKey("sticker_kits", /* bCreate = */ false)` then it only returns the first array (items 0-1).

**Comment by xPaw** [comment]
I tested it, and we have multiple sticker_kits in the children, so you have to iterate them yourself.

Closing as this isn't a bug and matches Valve's behaviour.
