### ISSUE TITLE
VKV can't parse KV when reading directly from HttpClient's stream using HttpCompletionOption.ResponseHeadersRead

### ISSUE THREAD

**Issue by JustArchi** [SteamDatabase/ValveKeyValue#48]
`HttpCompletionOption.ResponseHeadersRead` is a special option we can pass to `HttpClient` which allows to return the response as soon as 200 OK is returned (as opposed to full data), which allows the user to start parsing the data while it's still being buffered.

A repro below:

```csharp
private static async Task ReproNotWorking() {
    using HttpClient httpClient = new();

    using HttpRequestMessage request = new(HttpMethod.Get, new Uri("https://raw.githubusercontent.com/SteamDatabase/GameTracking-CSGO/master/csgo/resource/csgo_english.txt"));

    using HttpResponseMessage response = await httpClient.SendAsync(request, HttpCompletionOption.ResponseHeadersRead).ConfigureAwait(false);

    KVSerializer? serializer = KVSerializer.Create(KVSerializationFormat.KeyValues1Text);

    KVSerializerOptions options = new() {
        EnableValveNullByteBugBehavior = true,
        HasEscapeSequences = true
    };

    using Stream stream = await response.Content.ReadAsStreamAsync().ConfigureAwait(false);

    serializer.Deserialize(stream, options);
}
```

Throws:

```
ValveKeyValue.KeyValueException: Found end of file when another token type was expected.
 ---> System.InvalidOperationException: Attempted to finalize object while in state InObjectBetweenKeyAndValue.
```

The same repro using `HttpCompletionOption.ResponseContentRead` instead of `HttpCompletionOption.ResponseHeadersRead` fixes the issue.

For some reason VKV can't work in this scenario, my blind guess is that it doesn't wait for the end of the stream but rather stops parsing in the middle while more data is being buffered, in result crashing as if the data was cut somewhere in the middle.

The proper logic in this case would include reading stream to the very end, also when being buffered and not fully ready yet.

Could also be something entirely different, I don't know. However, it's nice to note that other deserializing libraries (`Newtonsoft.Json` tested) work in this scenario just fine.

**Comment by xPaw** [comment]
Is this because we use Peek/Read on StreamReader which is non blocking, or is there another issue at play here?

**Comment by JustArchi** [comment]
For reference, I'm working myself with the still-being-buffered stream like the one above in ASF, when downloading huge binary file (23 MB+) and writing it to `MemoryStream` as it comes.

Dumbed down implementation looks like that:

```csharp
using Stream stream = await response.Content.ReadAsStreamAsync().ConfigureAwait(false);

MemoryStream ms = new();

await using (ms.ConfigureAwait(false)) {
    ArrayPool<byte> bytePool = ArrayPool<byte>.Shared;

    byte[] buffer = bytePool.Rent(8192);

    try {
        while (stream.CanRead) {
            int read = await stream.ReadAsync(buffer.AsMemory(0, buffer.Length)).ConfigureAwait(false);

            if (read == 0) {
                break;
            }

            await ms.WriteAsync(buffer.AsMemory(0, read)).ConfigureAwait(false);
        }
    } finally {
        bytePool.Return(buffer);
    }

    // Do something with ms ready
}
```

Nothing really outstanding here, but `ReadAsync()` for sure waits for more data before returning it, not sure about peek.
