### ISSUE TITLE
Cannot deserialize into object if KeyValue Array starts with index > 0 or if there are gaps within the index.

### ISSUE THREAD

**Issue by tekgator** [SteamDatabase/ValveKeyValue#55]
Using your sample project [SteamAppInfo](https://github.com/SteamDatabase/SteamAppInfo) to deserialize appinfo.vdf works perfectly fine.

In addition I created a class to deserialize the appinfo.vdf into an object and here I get the issue that `InvalidOperationException` is thrown in case the array index within appdata.vdf doesn't start with a 0 or if the array index has gaps in between.

The issue seems to be within `ObjectCopier.IsArray` where  you actually do an index check within a for loop after converting the index. Since the index is starting with 1 or there might be a gap the function returns false due to no match with the index of the for loop:

https://github.com/SteamDatabase/ValveKeyValue/blob/41492b76968bf4fbfa88c2bf2726e61754241606/ValveKeyValue/ValveKeyValue/ObjectCopier.cs#L176-L187

Code looks like this:

```CSharp

using var stream = File.OpenRead(_cataloguePath);
using var reader = new BinaryReader(stream);

var magic = reader.ReadUInt32();

if (magic != Magic)
    throw new InvalidDataException($"Unknown magic header: {magic}");

_universe = (SteamUniverse)reader.ReadUInt32();

var deserializer = KVSerializer.Create(KVSerializationFormat.KeyValues1Binary);

List<DeserializedSteamCatalogue> deserializedSteamCatalogueList = new();
do
{
    var appId = reader.ReadUInt32();

    if (appId == 0)
        break;

    DeserializedSteamCatalogue item = new()
    {
        AppID = appId,
        Size = reader.ReadUInt32(),
        InfoState = reader.ReadUInt32(),
        LastUpdated = DateTime.UnixEpoch.AddSeconds(reader.ReadUInt32()),
        Token = reader.ReadUInt64(),
        Hash = new ReadOnlyCollection<byte>(reader.ReadBytes(20)),
        ChangeNumber = reader.ReadUInt32(),
        // !!!!! Problem is here -> Deserialize directly into object !!!!!
        Data = deserializer.Deserialize<DeserializedSteamCatalogue.DeserializedData>(stream),
        // !!!!! Problem is here -> Deserialize directly into object !!!!!
    };


    deserializedSteamCatalogueList.Add(item);
} while (true);


public class DeserializedSteamCatalogue
{
    public uint AppID { get; set; }
    public uint Size { get; set; }
    public uint InfoState { get; set; }
    public DateTime LastUpdated { get; set; }
    public ulong Token { get; set; }
    public ReadOnlyCollection<byte>? Hash { get; set; }
    public uint ChangeNumber { get; set; }
    public DeserializedData Data { get; set; } = new();

    public class DeserializedData
    {
        public class DscdConfig
        {
            public string ContentType { get; set; } = string.Empty;
            public string Installdir { get; set; } = string.Empty;
            public DscdLaunch[] Launch { get; set; } = Array.Empty<DscdLaunch>();
        }
        public class DscdLaunch
        {
            public string Executable { get; set; } = string.Empty;
            public string Type { get; set; } = string.Empty;
            public DscdLaunchConfig Config { get; set; } = new();
        }

        public class DscdLaunchConfig
        {
            public string OsList { get; set; } = string.Empty;
            public string OsArch { get; set; } = string.Empty;
        }

        public string AppID { get; set; } = string.Empty;
        public DscdConfig Config { get; set; } = new();
    }
}


```

The structured export of the appinfo looks like this (Recursive print of the KVObject):

```
Name: appinfo
	appid: 570
	Name: config
		installdir: dota 2 beta
		contenttype: 3
		Name: launch
			Name: 1
				executable: game\bin\win64\dota2.exe
				arguments: -steam +engine_experimental_drop_frame_ticks 1 +voice_fadeouttime 0 -prewarm_panorama
				Name: config
					oslist: windows
					osarch: 64
				Name: description_loc
					english: Play Dota 2
					sc_schinese: Play Dota 2
				description: Play Dota 2
			Name: 2
				executable: game/dota.sh
				arguments: +engine_experimental_drop_frame_ticks 1 +@panorama_min_comp_layer_dimension 0 -prewarm_panorama
				Name: config
					oslist: macos
				Name: description_loc
					english: Play Dota 2
					sc_schinese: Play Dota 2
				description: Play Dota 2

```

In this sample the "launch" array starts with Index 1 instead of 0 like for other games.
There are also games in appinfo.vdf which seem to have gaps in between the array index e.g. 0, 1, 3, 6 where it also fails.

For testing I have removed the for loop in the IsArray Method and it runs through without any problems. Not sure what the intention was for the check, at least in this use case it isn't needed.

**Comment by xPaw** [comment]
Do I understand you correctly that this will throw?
```
"a"
{
   "1" "first"
   "6" "sixth"
}
```

Does it only throw when trying to deserialize into `Type[]` arrays?

I can see why we check for gaps, because otherwise we would need to create empty elements to fill the gaps in.

**Comment by xPaw** [comment]
If you reduce the sample further to just `List<string>` does it also behave the same?

**Comment by tekgator** [comment]
In this case I get an `System.ArgumentException: 'Uninitialized Strings cannot be created.'`
But here it doesn't even matter if the index is correct or not.

```CSharp
var deserializedLibraries = serializer.Deserialize<List<string>>(stream);
```

**Comment by xPaw** [comment]
Can you try deserializing into a dictionary? That should fix the issue when keys are appids.

**Comment by tekgator** [comment]
It indeed works with a dictionary, no error thrown and Dictionary filled properly.
![image](https://user-images.githubusercontent.com/11077551/177885521-1b2b7490-c050-4908-9499-0a2e6e2f28e6.png)

Not sure if this is an issue to be resolved in the lib as this is clearly an array/list item or if Steam is just to lazy to adjust indexes when they remove an part of the array/list.

**Comment by yaakov-h** [comment]
IIRC, Steam's API doesn't actually have arrays, only numerically indexed dictionaries.

VKV will happily deserialise something to an array if it looks like an array, but if it not something that we can cleanly map to an array we'll reject it as you've seen.

**Comment by tekgator** [comment]
@yaakov-h: Thanks for the explanation. It works fine with a dictionary for me and it solved my problem. I'll just close it.
