### ISSUE TITLE
Can't deserialize shortcuts.vdf

### ISSUE THREAD

**Issue by SamusAranX** [SteamDatabase/ValveKeyValue#62]
First off, here are my shortcut item and container classes:

<details>
  <summary>Lengthy-ish C# code block</summary>

```cs
[Serializable]
internal class Shortcut
{
	[KVProperty("appid")]
	public uint AppID { get; set; }

	public string? AppName { get; set; }
	public string? Exe { get; set; }
	public string? StartDir { get; set; }

	[KVProperty("icon")]
	public string? Icon { get; set; }

	public string? ShortcutPath { get; set; }
	public string? LaunchOptions { get; set; }
	public bool IsHidden { get; set; }
	public bool AllowDesktopConfig { get; set; } = true;
	public bool AllowOverlay { get; set; } = true;
	public bool OpenVR { get; set; }
	public bool Devkit { get; set; }
	public uint DevkitGameID { get; set; }
	public uint DevkitOverrideAppID { get; set; }
	public DateTime? LastPlayTime { get; set; }
	public string? FlatpakAppID { get; set; }

	[KVProperty("tags")]
	public List<string>? Tags { get; set; }

	public override string ToString()
	{
		return $"({this.AppID}) {this.AppName}";
	}
}

[Serializable]
internal class ShortcutsVDF : IEnumerable<Shortcut>
{
	[KVProperty("shortcuts")]
	public List<Shortcut> Shortcuts { get; set; }

	#region IEnumerable

	public IEnumerator<Shortcut> GetEnumerator()
	{
		return this.Shortcuts.GetEnumerator();
	}

	IEnumerator IEnumerable.GetEnumerator()
	{
		return this.Shortcuts.GetEnumerator();
	}

	#endregion

	public static ShortcutsVDF Load(string filename)
	{
		using var fs = File.OpenRead(filename);
		var kv = KVSerializer.Create(KVSerializationFormat.KeyValues1Binary);
		var kvObject = kv.Deserialize<List<Shortcut>>(fs);
		var vdf = new ShortcutsVDF
		{
			Shortcuts = kvObject,
		};
		return vdf;
	}
}
```
</details>

Trying to load a shortcuts.vdf file via `ShortcutsVDF.Load()` causes an OverflowException on the `var kvObject = kv.Deserialize<List<Shortcut>>(fs);` line saying "Value was either too large or too small for a UInt32". Changing `AppID`'s type from uint to int (even though app IDs seem to be unsigned) changes the exception to a FormatException saying "Input string was not in a correct format".
What am I supposed to change about my code to make this work?

Here's the shortcuts.vdf I'm trying to deserialize. It was generated by Steam and contains only one item: [shortcuts.vdf.zip](https://github.com/SteamDatabase/ValveKeyValue/files/9732492/shortcuts.vdf.zip)

**Comment by xPaw** [comment]
int type is correct, not uint.

However your issue is that it fails on `DevkitGameID` because it's encoded as a string type in the vdf.

We also don't currently support Nullable or DateTime type conversions (`LastPlayTime` is an int).

**Comment by SamusAranX** [comment]
The nullables and the DateTime property were leftovers from an earlier attempt, my bad. I made the nullables non-nullable, added KVIgnore to the DateTime property and added another property that converts to and from timestamps, and made the Devkit properties into strings and now it deserializes without a hitch.

One small problem when trying to serialize that structure back into a VDF file:
![image](https://user-images.githubusercontent.com/676069/194527082-a5659de0-93ff-4c0a-81c6-dbc801073d1f.png)
The integers seem to be treated as strings. Steam doesn't seem super bothered by this, but (and please correct me if I'm wrong) it's a problem because those IDs are used to keep track of custom library artwork. If they change because my program makes an unrelated edit, that artwork vanishes from the library.

I haven't yet tried de/serializing the file to/from generic keyvalue objects.

**Comment by xPaw** [comment]
It's very possible that we somehow manage to lose the type when converting from strongly typed object.

It would be perfect if you could make a reduced test case similar to tests here: https://github.com/SteamDatabase/ValveKeyValue/tree/master/ValveKeyValue/ValveKeyValue.Test/Binary

**Comment by SamusAranX** [comment]
I'll try to construct such a test case at some point.

In the meantime, I added a method `ToKVObject()` to my Shortcut model class to aid with VDF serialization:
```cs
public KVObject ToKVObject(int index)
{
	var kv = new KVObject(index.ToString(), Array.Empty<KVObject>())
	{
		["appid"] = this.AppID,
		["AppName"] = this.AppName,
		["Exe"] = this.Exe,
		["StartDir"] = this.StartDir,
		["icon"] = this.Icon,
		["ShortcutPath"] = this.ShortcutPath,
		["LaunchOptions"] = this.LaunchOptions,
		["IsHidden"] = this.IsHidden ? 1 : 0,
		["AllowDesktopConfig"] = this.AllowDesktopConfig ? 1 : 0,
		["AllowOverlay"] = this.AllowOverlay ? 1 : 0,
		["OpenVR"] = this.OpenVR ? 1 : 0,
		["Devkit"] = this.Devkit ? 1 : 0,
		["DevkitGameID"] = this.DevkitGameID,
		["DevkitOverrideAppID"] = this.DevkitOverrideAppID,
		["LastPlayTime"] = this.LastPlayTimeUnix,
		["FlatpakAppID"] = this.FlatpakAppID,
	};

	var tagsList = new List<KVObject>();
	for (var i = 0; i < this.Tags.Count; i++)
	{
		var kvTag = new KVObject(i.ToString(), this.Tags[i]);
		tagsList.Add(kvTag);
	}
	kv.Add(new KVObject("tags", tagsList));

	return kv;
}
		
```

This, in combination with the untyped serializer, generates the exact same VDF file Steam does.

**Comment by xPaw** [comment]
I've added a (failing) test for the serialization bug: #64

As well as the DateTime issue: #63
