### ISSUE TITLE
IntPtr does not serialize to text

### ISSUE THREAD

**Issue by xPaw** [SteamDatabase/ValveKeyValue#65]
```csharp
        class DataObject
        {
            public IntPtr VPointer { get; set; }
        }
```

this serializes to: `"VPointer"\n\t\t{\n\t\t}`

FYI IntPtr is not IConvertible.

**Comment by yaakov-h** [comment]
Valve don't support writing TYPE_PTR to text, so we have no reference to go off. They only write TYPE_PTR when doing binary serialization.

There's also this interesting comment in the 64-bit parser code:

> We need to ensure we only read 32 bits out of the stream because 32 bit clients only wrote 32 bits of data there. The actual pointer is irrelevant, **all that we really care about here contractually is whether the pointer is zero or not zero**.

**Comment by xPaw** [comment]
Even for binary serialization it somewhat worked due to everything to become a string in object copier.

Since I had to fix that to preserve types, I had to fix it to preserve Pointer type: https://github.com/SteamDatabase/ValveKeyValue/pull/64/commits/db41cf8127fd50aa2e807c59996a1843fe2f7338

With that, the conversion works now (because our KVValue operator casts it to int).

**Comment by xPaw** [comment]
It works now by converting to int, but as we discussed we're leaving it undefined behaviour and not testing.
