### ISSUE TITLE
Implement schema text

### ISSUE THREAD

**Issue by xPaw** [SteamDatabase/ValveKeyValue#7]
Example file: https://github.com/MNoya/DotaCraft/blob/7791535a1977610defffb815aab58617235546da/content/dota_addons/dotacraft/models/elven_farm.vmdl

**Comment by SinZ163** [comment]
Appears to be a deprecated format of valves, as it got replaced by KV3 for particles at reborn launch, but a couple of observations:

* It starts off with a header near identical to KV3's, 
`<!-- schema text {7e125a45-3d83-4043-b292-9e24f8ef27b4} generic {198980d8-3a93-4919-b4c6-dd1fb07a3a4b} -->`

* It has two methods of defining arrays, [`DataType[] array = [value, value2, value3]`](https://github.com/MNoya/DotaCraft/blob/7791535a1977610defffb815aab58617235546da/content/dota_addons/dotacraft/particles/auras/aura5.vpcf#L48-L51) and [`DataType(n) array = (value, value2, value3, valuen)`](https://github.com/MNoya/DotaCraft/blob/7791535a1977610defffb815aab58617235546da/content/dota_addons/dotacraft/particles/auras/aura5.vpcf#L6). The former is multi line, the later is inline. (potentially object vs primitive)
* It has "pointer" support for object arrays, marked by [DataType*[]](https://github.com/MNoya/DotaCraft/blob/7791535a1977610defffb815aab58617235546da/content/dota_addons/dotacraft/particles/auras/aura5.vpcf#L56), and [&ValueVariable](https://github.com/MNoya/DotaCraft/blob/7791535a1977610defffb815aab58617235546da/content/dota_addons/dotacraft/particles/auras/aura5.vpcf#L58).
* Defines objects by [`DataType {}`](https://github.com/MNoya/DotaCraft/blob/7791535a1977610defffb815aab58617235546da/content/dota_addons/dotacraft/models/elven_farm.vmdl#L46-L50) and [`DataType variable = DataType {}`](https://github.com/MNoya/DotaCraft/blob/7791535a1977610defffb815aab58617235546da/content/dota_addons/dotacraft/models/elven_farm.vmdl#L60-L64) with root objects just being [`DataType variable {}`](https://github.com/MNoya/DotaCraft/blob/7791535a1977610defffb815aab58617235546da/content/dota_addons/dotacraft/models/elven_farm.vmdl#L123-L133)
* Appears to have int, uint, float, string, bool and symbol as primitives.
* symbol appears to be able to be [natural numbers](https://github.com/MNoya/DotaCraft/blob/7791535a1977610defffb815aab58617235546da/content/dota_addons/dotacraft/particles/auras/aura5.vpcf#L346), and as the [`STATIC` keyword](https://github.com/MNoya/DotaCraft/blob/7791535a1977610defffb815aab58617235546da/content/dota_addons/dotacraft/models/elven_farm.vmdl#L30)
* float appears to be formatted to have [6 decimal places](https://github.com/MNoya/DotaCraft/blob/7791535a1977610defffb815aab58617235546da/content/dota_addons/dotacraft/models/elven_farm.vmdl#L33).
