### ISSUE TITLE
KVObject should implement IList<T>

### ISSUE THREAD

**Issue by HiddenDot** [SteamDatabase/ValveKeyValue#78]
I would like to be able to add/remove children to/from a `KVObject`. I would also like the ability to get the number of children in a `KVObject` without having to enumerate it.
I suggest having the `KVObject` class implement the `System.Collections.Generic.ICollection<T>` and `System.Collections.Generic.IList<T>` interfaces. This would also enable getting/setting children by index, thus allowing to enumerate via a `for` loop.

Thank you for considering my suggestion.

**Comment by yaakov-h** [comment]
KVObjects were intended to be immutable, but we need to do some work in the space to simplify it for consumers.

See #30 and #21 which already cover improving the API.

**Comment by yaakov-h** [comment]
> **intended** to be immutable
